### ISSUE TITLE
How to use vue-cli-plugin-moment?

### ISSUE THREAD

**Issue by irfandyj** [scottbedard/vue-cli-plugin-moment#3]
This seems to be a dumb question, but how do I use this plugin?
I tried importing it
```
import Moment from 'moment' // failed
var moment = require('moment') // failed
```
But it seems to be not working.. I don't understand much with Vue CLI 3.0 yet, so I just randomly `vue add 'plugin'` everytime `vue-cli-plugin-` is available.. Did I miss some requirement or something? Thank you.

**Comment by scottbedard** [comment]
Hi, you'll need to install moment separately, sorry if that wasn't clear. This plugin simply configures webpack's inclusion of moment locales because I didn't want to force people into using any specific version of moment.

A simple `yarn add moment` should fix your problem, let me know if you still have trouble.
